[build]
  publish = "dist"  # Folder build output Vite, biasanya "dist"
  command = "npm run build"  # Perintah untuk menjalankan build

# Jika diperlukan, tambahkan environment variable untuk menentukan versi Node.js
[build.environment]
  NODE_VERSION = "18.0.0"  # Sesuaikan dengan versi Node.js proyekmu

